/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Traveling_Management_System;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import Traveling_Management_System.Travel_Management_System;

public class Login_System extends javax.swing.JFrame {

    /**
     * Creates new form Login_System
     */
    public Login_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUserName = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabel2.setText("LOGIN TO ENTER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 440, 100);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 45)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 260, 239, 52);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 45)); // NOI18N
        jLabel3.setText("USER NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 239, 52);

        jPassword.setBackground(new java.awt.Color(204, 204, 255));
        jPassword.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jPassword);
        jPassword.setBounds(400, 260, 230, 60);

        jUserName.setBackground(new java.awt.Color(204, 204, 255));
        jUserName.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 45)); // NOI18N
        jUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jUserName);
        jUserName.setBounds(400, 180, 230, 60);

        login.setBackground(new java.awt.Color(255, 255, 51));
        login.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 25)); // NOI18N
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(80, 390, 120, 70);

        reset.setBackground(new java.awt.Color(255, 255, 51));
        reset.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 25)); // NOI18N
        reset.setText("RESET");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(300, 390, 120, 70);

        Exit.setBackground(new java.awt.Color(255, 255, 51));
        Exit.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 25)); // NOI18N
        Exit.setText("EXIT");
        Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(510, 390, 120, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Travel23.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        jUserName.setText(null);
        jPassword.setText(null);           // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        String password = jPassword.getText();
        String username = jUserName.getText();

        if (password.contains("10549") && (username.contains("istiyak"))) {
            jUserName.setText(null);
            jPassword.setText(null);
            systemExit();

            Travel_Management_System Info = new Travel_Management_System();
            Info.setVisible(true);
            
        } 
        
        else if (password.contains("10846") && (username.contains("udoy"))) {
            jUserName.setText(null);
            jPassword.setText(null);
            systemExit();

            Travel_Management_System Info = new Travel_Management_System();
            Info.setVisible(true);
        }
        
        else if (password.contains("10545") && (username.contains("shahriar"))) {
            jUserName.setText(null);
            jPassword.setText(null);
            systemExit();

            Travel_Management_System Info = new Travel_Management_System();
            Info.setVisible(true);
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
            jPassword.setText(null);
            jUserName.setText(null);
        }
        
       
// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUserName;
    private javax.swing.JButton login;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

    private void systemExit() {
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }

}
